export enum RelationType {
  INNER_JOIN = 'INNER JOIN',
  JOIN = 'JOIN',
  LEFT_OUTER_JOIN = 'LEFT OUTER JOIN',
  RIGHT_OUTER_JOIN = 'RIGHT OUTER JOIN',
  FULL_OUTER_JOIN = 'FULL OUTER JOIN',
  CROSS_JOIN = 'CROSS JOIN',
}
